
# for parallel processing
number_of_processors: 8

# temporary location for khajuri and caffe paths - will get
# these from environment variable in the future
khajur_root: /home/ubuntu/khajuri
caffe_root: /home/ubuntu/chia/caffe


# for faster operations, provide tempfs location for intermediate computation
# not used currently
tempfs: /mnt/tmp/SyntheticData

# Dimension of patches
output_width:    256
output_height:   256

# generate positive patches from annotated positive images
positive_patch:
  is_test:                                    false
  folders:
    image_input:                              images
    annotation_input:                         annotations
  # reccommended: the area of min_object_dimensions be at least 5%
  # of area of extracted patch - signal to noise needs to be at least 5%
  min_object_area_fraction:                   0.05
  transformations:
    jiggles:
      fraction_to_keep:                       0.5
      max_num_jiggles:                        5
      min_pixel_move:                         50
    shear:
      num_shear:                              5
    scaling:
      down_scale_times:                       3
      up_scale_times:                         3
      scale_factor:                           0.2

# generate negative patches from annotated positive images
negative_patch_from_positive:
  is_test:                                    false
  folders:
    image_input:                              images
    annotation_input:                         annotations
  number_of_patch_per_image:                  5

# generate negative patches from a non-annotated images
negative_patch:
  is_test:                                    false
  folders:
    include_sub_folders:                      no
  number_of_patch_per_image:                  5

# Sliding window configurations
sliding_window:
  is_test:                                    false
  folders:
    patch_output:                             patches
    annotation_output:                        annotations
  frame_density:                              5
  x_stride:                                   128
  y_stride:                                   128
  scaling:
    - 1.0
    - 0.8
    - 0.6
    - 0.4
    - 1.2

# Video testing configuration - in addition to sliding window above
video_testing:
  background_classes:
    - 0
  caffe_batch_size:                           50
  use_gpu:                                    true

# Test dataset set up
dataset_setup:
  # dataset_type can be 'train_test', 'split_data', 'test_only'
  dataset_type:        train_test
  # data set split for training/testing - has to add up to 1.0
  dataset_split:
    train: 0.7
    validation: 0.0
    test: 0.3

