# class we are interested in
class_name: adidas-long

# for parallel processing
max_number_of_threads: 2

# base folders to which the folder names below will be concatenated
input_base_folder: /home/evan/Vision/Scripts/TextGeneration/temp/annotation_matlab/input
output_base_folder: /home/evan/Vision/Scripts/TextGeneration/temp/annotation_matlab/output

runs:
  crop_positive_patch:
    current:                                  false
    input_images_folder:                      images
    input_annotations_folder:                 annotations
    output_folder:                            positive_patch
  crop_negative_patch:
    current:                                  false
    input_images_folder:                      images
    input_annotations_folder:                 none
    include_sub_folders:                      yes
    output_folder:                            negative_patch
    number_of_patch_per_image:                5
  crop_negative_patch_from_positive:
    current:                                  false
    input_images_folder:                      images
    input_annotations_folder:                 annotations
    output_folder:                            negative_patch
    number_of_patch_per_image:                5
  test_positive_patch:
    current:                                  true
    input_images_folder:                      images
    input_annotations_folder:                 annotations
    output_folder:                            test_results
  test_negative_patch:
    current:                                  false
    input_images_folder:                      images
    input_annotations_folder:                 none
    include_sub_folders:                      yes
    output_folder:                            test_results
    number_of_patch_per_image:                5
  test_negative_patch_from_positive:
    current:                                  false
    input_images_folder:                      images
    input_annotations_folder:                 annotations
    output_folder:                            test_results
    number_of_patch_per_image:                5


# for faster operations, provide tempfs location for intermediate computation
# not used currently
tempfs: /mnt/tmp/SyntheticData

# dimension for output patches - for now, only squares supported
output_width:    256
output_height:   256

# synthetic data setting
# NOT DONE YET

# data set split for training/testing - has to add up to 1.0
dataset_split:
  train: 0.7
  validation: 0.0
  test: 0.3

