# class we are interested in
class_name: adidas-long

# for parallel processing - currently, it uses all processors
multi_threaded: true

# the following folders are subfolders of inputBaseFolder and outputBaseFolder
# specified from command line
runs:
  crop_positive_patch:
    current:                                  false
    input_images_folder:                      images
    input_annotations_folder:                 annotations
    output_folder:                            positive_patch
  crop_negative_patch:
    current:                                  false
    input_images_folder:                      images
    input_annotations_folder:                 none
    include_sub_folders:                      yes
    output_folder:                            negative_patch
    number_of_patch_per_image:                5
  crop_negative_patch_from_positive:
    current:                                  false
    input_images_folder:                      images
    input_annotations_folder:                 annotations
    output_folder:                            negative_patch_from_positive
    number_of_patch_per_image:                5
  crop_sliding_window:
    current:                                  false
    input_images_folder:                      images
    input_annotations_folder:                 none
    output_folder:                            sliding_window
  test_positive_patch:
    current:                                  true
    input_images_folder:                      images
    input_annotations_folder:                 annotations
    output_folder:                            test_results
  test_negative_patch:
    current:                                  false
    input_images_folder:                      images
    input_annotations_folder:                 none
    include_sub_folders:                      yes
    output_folder:                            test_results
    number_of_patch_per_image:                5
  test_negative_patch_from_positive:
    current:                                  false
    input_images_folder:                      images
    input_annotations_folder:                 annotations
    output_folder:                            test_results
    number_of_patch_per_image:                5
  test_sliding_window:
    current:                                  false
    input_images_folder:                      images
    input_annotations_folder:                 none
    output_folder:                            test_results


# for faster operations, provide tempfs location for intermediate computation
# not used currently
tempfs: /mnt/tmp/SyntheticData

# dimension for output patches - for now, only squares supported
output_width:    256
output_height:   256

sliding_window:
    x_stride:                                 128
    y_stride:                                 128
    down_scale_times:                         1
    up_scale_times:                           0
    scale_factor:                             0.5


# synthetic data setting
# NOT DONE YET


# dataset set up
dataset_setup:
  # dataset_type can be 'train_test', 'split_data', 'test_only'
  dataset_type:        test_only
  # data set split for training/testing - has to add up to 1.0
  dataset_split:
    train: 0.7
    validation: 0.0
    test: 0.3

